### ISSUE TITLE
Engagement stream

### ISSUE THREAD

**Issue by joostschouppe** [pietervdvn/pietervdvn.github.io#3]
How can we trigger people to make an account?
Idea for a little flow when you click "save", you get a screen with:
- already have an OSM account? Click here to connect or make one now
- No account? Please fill in your e-mail address so we can ask additional questions if needed
- Want to share anonymously? We can't promise anything, but we'll share the info with the community

**Comment by pietervdvn** [comment]
Should be fixed in the current MapComplete
